[book]
authors = ["RemiIO"]
language = "zh-CN"
title = "Kigurumi 不完全手册"
src = "./"
description = "个记录 Kigurumi 知识、经验、资源的手册，这里有一些关于 Kigurumi 的基础知识、自制经验、活跃玩家、工坊店家、活动等等。致力于成为能覆盖到 Kigurumi 爱好者 play 的全生命周期手册"